services:
  - type: web
    name: grievanceiq-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ML_SERVICE_URL
        fromService:
          type: web
          name: grievanceiq-ml
          envVarKey: RENDER_EXTERNAL_URL
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: grievanceiq-redis
          property: connectionString

  - type: web
    name: grievanceiq-ml
    env: python
    rootDir: backend/ml
    buildCommand: pip install -r requirements.txt
    startCommand: python inference/grievanceiq_inference.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12

  - type: redis
    name: grievanceiq-redis
    ipAllowList: [] # internal connections only
    plan: free
