-- Phase 1 Migration: Add embedding_vector to complaints table
-- GrievanceIQ AI Pipeline - Phase 1: Semantic Embedding & Similarity Engine
-- Model: sentence-transformers/all-MiniLM-L6-v2 (384 dimensions)

-- 1. Add embedding_vector column as float8[] (array of 64-bit floating point numbers)
-- This natively stores the 384-dimensional dense semantic embedding without requiring external extensions.
ALTER TABLE public.complaints
  ADD COLUMN IF NOT EXISTS embedding_vector float8[] DEFAULT '{}';

-- 2. Comment on column for schema documentation
COMMENT ON COLUMN public.complaints.embedding_vector IS '384-dimensional semantic embedding vector generated by Xenova/all-MiniLM-L6-v2 for semantic similarity and duplicate detection';
-- Phase 2 Migration: Add duplicate detection diagnostic columns to complaints table
-- GrievanceIQ AI Pipeline - Phase 2: Real Duplicate Detection
--
-- Prerequisite: Phase 1 migration (embedding_vector) must have been run first.
-- Run this in your Supabase SQL Editor after phase1_embedding.sql.

-- 1. Add numeric duplicate score (weighted combination of semantic + location + temporal)
ALTER TABLE public.complaints
  ADD COLUMN IF NOT EXISTS duplicate_score numeric DEFAULT 0;

-- 2. Add reference to the complaint this was matched against
ALTER TABLE public.complaints
  ADD COLUMN IF NOT EXISTS duplicate_candidate_id uuid REFERENCES public.complaints(id) ON DELETE SET NULL;

-- 3. Add individual diagnostic scores for debugging / demonstration
ALTER TABLE public.complaints
  ADD COLUMN IF NOT EXISTS duplicate_semantic_score numeric DEFAULT 0;

ALTER TABLE public.complaints
  ADD COLUMN IF NOT EXISTS duplicate_location_score numeric DEFAULT 0;

ALTER TABLE public.complaints
  ADD COLUMN IF NOT EXISTS duplicate_temporal_score numeric DEFAULT 0;

-- 4. Documentation comments
COMMENT ON COLUMN public.complaints.duplicate_score IS 'Weighted duplicate score: 0.50*semantic + 0.30*location + 0.20*temporal';
COMMENT ON COLUMN public.complaints.duplicate_candidate_id IS 'UUID of the existing complaint this was identified as a duplicate of';
COMMENT ON COLUMN public.complaints.duplicate_semantic_score IS 'Cosine similarity between MiniLM embeddings (0-1)';
COMMENT ON COLUMN public.complaints.duplicate_location_score IS 'Haversine proximity score (0-1, decays over 500m radius)';
COMMENT ON COLUMN public.complaints.duplicate_temporal_score IS 'Temporal proximity score (0-1, decays over 48h window)';
-- Phase 4 Migration: Create Civic Issues Table and Link Complaints
-- GrievanceIQ AI Pipeline - Phase 4: Civic Knowledge Graph + Connected Components

-- 1. Create civic_issues table
CREATE TABLE IF NOT EXISTS public.civic_issues (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  description text,
  primary_category text,
  priority text DEFAULT 'Medium',
  status text DEFAULT 'Open',
  location_lat numeric,
  location_lng numeric,
  complaint_ids uuid[] DEFAULT '{}',
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- 2. Add civic_issue_id to complaints table
ALTER TABLE public.complaints
  ADD COLUMN IF NOT EXISTS civic_issue_id uuid REFERENCES public.civic_issues(id) ON DELETE SET NULL;

-- 3. Documentation comments
COMMENT ON TABLE public.civic_issues IS 'Aggregated civic issues formed by connected components of related/duplicate complaints';
COMMENT ON COLUMN public.complaints.civic_issue_id IS 'UUID of the civic issue this complaint is grouped into';
-- Phase 5 Migration: Create Routing, Workstreams, and Tasks
-- GrievanceIQ AI Pipeline - Phase 5: Multi-Department Routing + Task Generation

-- 1. Create workstreams table
CREATE TABLE IF NOT EXISTS public.workstreams (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  civic_issue_id uuid REFERENCES public.civic_issues(id) ON DELETE CASCADE,
  department_id text NOT NULL, -- Storing the department name string as requested (e.g. "Water Department")
  issue_types text[] DEFAULT '{}',
  status text DEFAULT 'PENDING',
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(civic_issue_id, department_id) -- Idempotency: One workstream per department per civic issue
);

-- 2. Create tasks table
CREATE TABLE IF NOT EXISTS public.tasks (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  civic_issue_id uuid REFERENCES public.civic_issues(id) ON DELETE CASCADE,
  workstream_id uuid REFERENCES public.workstreams(id) ON DELETE CASCADE,
  department_id text NOT NULL,
  issue_type text NOT NULL,
  title text NOT NULL,
  description text,
  status text DEFAULT 'PENDING',
  priority text DEFAULT 'Medium',
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(civic_issue_id, issue_type, title) -- Idempotency: Prevent duplicate tasks for the same issue
);

-- 3. Create routing_results table (Optional, for caching/explainability)
CREATE TABLE IF NOT EXISTS public.routing_results (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  civic_issue_id uuid REFERENCES public.civic_issues(id) ON DELETE CASCADE UNIQUE,
  issue_types jsonb DEFAULT '[]',
  departments jsonb DEFAULT '[]',
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- 4. Create Indexes
CREATE INDEX IF NOT EXISTS idx_workstreams_civic_issue_id ON public.workstreams(civic_issue_id);
CREATE INDEX IF NOT EXISTS idx_tasks_civic_issue_id ON public.tasks(civic_issue_id);
CREATE INDEX IF NOT EXISTS idx_tasks_workstream_id ON public.tasks(workstream_id);

-- 5. Documentation
COMMENT ON TABLE public.workstreams IS 'Department-specific workstreams generated from a Civic Issue';
COMMENT ON TABLE public.tasks IS 'Actionable operational tasks generated from deterministic templates';
COMMENT ON TABLE public.routing_results IS 'Stored results of the multi-label classification and department routing process';
-- Phase 6 Migration: Task Dependencies DAG
-- GrievanceIQ AI Pipeline - Phase 6: Task Dependencies + Execution Order

CREATE TABLE IF NOT EXISTS public.task_dependencies (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  task_id uuid REFERENCES public.tasks(id) ON DELETE CASCADE,
  depends_on_task_id uuid REFERENCES public.tasks(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  
  -- Ensure a task cannot depend on itself
  CONSTRAINT no_self_dependency CHECK (task_id != depends_on_task_id),
  
  -- Ensure no duplicate dependency records
  UNIQUE(task_id, depends_on_task_id)
);

CREATE INDEX IF NOT EXISTS idx_task_dependencies_task_id ON public.task_dependencies(task_id);
CREATE INDEX IF NOT EXISTS idx_task_dependencies_depends_on ON public.task_dependencies(depends_on_task_id);

COMMENT ON TABLE public.task_dependencies IS 'Directed edges representing task dependencies (task_id must wait for depends_on_task_id to finish)';
-- Phase 7 Migration: Task Execution & Progress Tracking
-- GrievanceIQ AI Pipeline

-- 1. Add timestamp fields to tasks table
ALTER TABLE public.tasks 
ADD COLUMN IF NOT EXISTS started_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS cancelled_at timestamp with time zone;

-- 2. Create task_status_history table for auditing
CREATE TABLE IF NOT EXISTS public.task_status_history (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  task_id uuid REFERENCES public.tasks(id) ON DELETE CASCADE,
  previous_status text NOT NULL,
  new_status text NOT NULL,
  changed_by text, -- Ideally user ID or email
  reason text,
  changed_at timestamp with time zone DEFAULT now()
);

-- 3. Create indexes for quick history retrieval
CREATE INDEX IF NOT EXISTS idx_task_status_history_task_id ON public.task_status_history(task_id);
CREATE INDEX IF NOT EXISTS idx_task_status_history_changed_at ON public.task_status_history(changed_at);

-- 4. Documentation
COMMENT ON TABLE public.task_status_history IS 'Audit log of all manual task status transitions and the user who triggered them';
-- Phase 8 Migration: Task Hardening & Transaction Safety
-- Adds template_id to tasks for stable dependencies

-- 1. Add template_id column
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS template_id text;

-- 2. Drop the old unique constraint (civic_issue_id, issue_type, title)
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_civic_issue_id_issue_type_title_key;

-- 3. Add the new unique constraint (civic_issue_id, template_id)
ALTER TABLE public.tasks ADD CONSTRAINT tasks_civic_issue_id_template_id_key UNIQUE (civic_issue_id, template_id);

-- 4. Create the Stored Procedure for atomic transaction safety
CREATE OR REPLACE FUNCTION public.update_task_status_transactional(
  p_task_id uuid,
  p_new_status text,
  p_user_email text,
  p_reason text
)
RETURNS void AS $$
DECLARE
  v_civic_issue_id uuid;
  v_workstream_id uuid;
  v_current_status text;
  
  v_ws_all_cancelled boolean;
  v_ws_all_finished boolean;
  v_ws_none_started boolean;
  v_ws_new_status text;
  
  v_issue_all_cancelled boolean;
  v_issue_all_finished boolean;
  v_issue_none_started boolean;
  v_issue_new_status text;
BEGIN
  -- 1. Lock the task and get details
  SELECT civic_issue_id, workstream_id, status 
  INTO v_civic_issue_id, v_workstream_id, v_current_status
  FROM public.tasks 
  WHERE id = p_task_id 
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Task not found';
  END IF;
  
  IF v_current_status = p_new_status THEN
    RETURN; -- No change
  END IF;

  -- 2. Update Task
  UPDATE public.tasks 
  SET 
    status = p_new_status, 
    started_at = CASE WHEN p_new_status = 'IN_PROGRESS' AND v_current_status = 'PENDING' THEN now() ELSE started_at END,
    completed_at = CASE WHEN p_new_status = 'COMPLETED' THEN now() ELSE completed_at END,
    cancelled_at = CASE WHEN p_new_status = 'CANCELLED' THEN now() ELSE cancelled_at END,
    updated_at = now() 
  WHERE id = p_task_id;

  -- 3. Audit Log
  INSERT INTO public.task_status_history 
    (task_id, previous_status, new_status, changed_by, reason)
  VALUES 
    (p_task_id, v_current_status, p_new_status, COALESCE(p_user_email, 'system'), COALESCE(p_reason, 'Transitioned to ' || p_new_status));

  -- 4. Re-evaluate Workstream Status
  SELECT 
    bool_and(status = 'CANCELLED'),
    bool_and(status IN ('COMPLETED', 'CANCELLED')),
    bool_and(status = 'PENDING')
  INTO v_ws_all_cancelled, v_ws_all_finished, v_ws_none_started
  FROM public.tasks
  WHERE workstream_id = v_workstream_id;
  
  IF v_ws_all_cancelled THEN v_ws_new_status := 'CANCELLED';
  ELSIF v_ws_all_finished THEN v_ws_new_status := 'COMPLETED';
  ELSIF NOT v_ws_none_started THEN v_ws_new_status := 'IN_PROGRESS';
  ELSE v_ws_new_status := 'PENDING';
  END IF;
  
  UPDATE public.workstreams 
  SET status = v_ws_new_status, updated_at = now() 
  WHERE id = v_workstream_id;

  -- 5. Re-evaluate Civic Issue Status
  SELECT 
    bool_and(status = 'CANCELLED'),
    bool_and(status IN ('COMPLETED', 'CANCELLED')),
    bool_and(status = 'PENDING')
  INTO v_issue_all_cancelled, v_issue_all_finished, v_issue_none_started
  FROM public.tasks
  WHERE civic_issue_id = v_civic_issue_id;

  IF v_issue_all_cancelled THEN v_issue_new_status := 'CANCELLED';
  ELSIF v_issue_all_finished THEN v_issue_new_status := 'COMPLETED';
  ELSIF NOT v_issue_none_started THEN v_issue_new_status := 'IN_PROGRESS';
  ELSE v_issue_new_status := 'PENDING';
  END IF;

  UPDATE public.civic_issues 
  SET status = v_issue_new_status, updated_at = now() 
  WHERE id = v_civic_issue_id;

END;
$$ LANGUAGE plpgsql;
-- Phase 10: Multilabel Issue Classification Support
-- Adds persistence for the trained Python ML inference outputs to the complaints table.

ALTER TABLE complaints
ADD COLUMN IF NOT EXISTS ml_labels TEXT[],
ADD COLUMN IF NOT EXISTS ml_probabilities JSONB,
ADD COLUMN IF NOT EXISTS ml_departments TEXT[];

-- Optional: Create an index for querying complaints by ML label
CREATE INDEX IF NOT EXISTS idx_complaints_ml_labels ON complaints USING GIN (ml_labels);
