-- Phase 1 Migration: Add embedding_vector to complaints table
-- GrievanceIQ AI Pipeline - Phase 1: Semantic Embedding & Similarity Engine
-- Model: sentence-transformers/all-MiniLM-L6-v2 (384 dimensions)

-- 1. Add embedding_vector column as float8[] (array of 64-bit floating point numbers)
-- This natively stores the 384-dimensional dense semantic embedding without requiring external extensions.
ALTER TABLE public.complaints
  ADD COLUMN IF NOT EXISTS embedding_vector float8[] DEFAULT '{}';

-- 2. Comment on column for schema documentation
COMMENT ON COLUMN public.complaints.embedding_vector IS '384-dimensional semantic embedding vector generated by Xenova/all-MiniLM-L6-v2 for semantic similarity and duplicate detection';
